export const worldMaps = {
  sunmeadow: {
    name: "Sunmeadow",
    palette: { top: "#78c98b", bottom: "#5ea96f" },
    encounterRate: 0.085,
    terrain: [
      "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
      "WRRTTTGGGGGGGGGGGGGGGGGGGGGGGGGwGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGW",
      "WRRTTTTGGGGGGGGGGGGGGTTTTGGGGGGwGGGGGGGGGGGGGGGGGGGGTTTTTTTWWGGGGGGGGGGW",
      "WRRTTTTGGGWWGGGGGGGGGGTTTTGGGGGWWWWWWWWWWWWWRRRWWWWWWWWWWWWWWWWWWWWWWWWW",
      "WRRTTTTGGGWWGGGGGGGGGGGGGGGGGGGWGGGGGGGGGGGGRRRGGGGGGGGGGGGGGGGGGGGGGGGW",
      "WRRRRRTTTGGGGGGGGGGGGGGGGGGGGGGWGGGGGGGGGGGGRRRGGGGGGGGGGGGGGGGGGGGGGGGW",
      "WRRRRRTGTTTTTGGGGGGGGGTTTTGGGGGWTTTTTTTTTTTTRRRTTTTTTTTTTTTTTTTTTTTTTTTW",
      "WTTTTTTTTTTTTGGGGGGGGGTTTTGGGGGWTTTTTTTTTTTTRRRTTTTTTTTTTTTTTTTTTTTTTTTW",
      "WGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWTTTTTTTTTTTTRRRTTTTTTTTTTTTTTTTTTTTTTTTW",
      "WGGGGTTTGGGGGGGGGGGGGGGGGGGGGGGWTTTTTTTTTTTTTRRRRRRTTTTTTTTTTTTTTTTTTTTW",
      "WGGGGTTTGGGGGGGGGGGGGGGGRRGGGGGWTTTTTTTTTTTTTRRRRRRTTTTTTTTTTTTTTTTTTTTW",
      "WGGGGGGGGGGGGGGGGGGGGGGGRRGGGGGWTTTTTTTTTTTTTTTTRRRTTTTTTTTTTTTTTTTTTTTW",
      "WGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWTTTTTTTTTTTTTTTTRRRTTTTTTTTTTTTTTTTTTTTW",
      "WGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWWWWWWWWWWWWWWWRRRWWWWWWWWWWWWWWWWWWWWW",
      "WGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRW",
      "WGGGGGGGGGGGTTTTGGGGGGGGGGGGGGGWRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRW",
      "WGGGGGGGGGGGTTTTGGGGGGGGGGGGGGGWRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRW",
      "WGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRW",
      "WGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRW",
      "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
    ],
    signs: [
      { x: 5, y: 5, text: "Tall grass is alive with angry creatures beware." },
      { x: 21, y: 11, text: "Player tip: press Enter to open your menu." },
      { x: 25, y: 4, text: "A cave mouth waits to the east. Stay alert." },
      { x: 47, y: 14, text: "Welcome to New Town." }
    ],
    triggers: [
      {
        x: 27,
        y: 5,
        kind: "cave",
        targetMap: "emberCave",
        targetX: 2,
        targetY: 12,
        message: "You step into Ember Cave."
      },
      {
        x: 23,
        y: 12,
        kind: "door",
        targetMap: "wayfarerHouse",
        targetX: 4,
        targetY: 6,
        message: "You enter the wayfarer's cottage."
      },
      {
        x: 68,
        y: 2,
        kind: "cave",
        targetMap: "emberCave",
        targetX: 44,
        targetY: 13,
        message: "You step into Ember Cave."
      }
    ]
  },
  emberCave: {
    name: "Ember Cave",
    palette: { top: "#635166", bottom: "#362933" },
    encounterRate: 0.14,
    terrain: [
      "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
      "WWGGGGGGGGGGGGGGGGGGGGWGGGGGGGGGGGGGGGGGGGGGGGGGGGGTTTTTTW",
      "WGGGGGGGGGGGGGGGGGGGGGGTTTTTTTGGGGGGGTTTTTTTTTTTTGGGGGGGGW",
      "WGGGGGGWWWWWGGGGGGGGGGGWWWWWWWWWWWWWWWWWWWWWWWWWWWWWTTTTTW",
      "WGGGGGGWGGGWGGGGGGGGGGGWTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTW",
      "WGGGTTTWGGGWGGGGTTTGGGGWWTTTTTWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
      "WGGGTTTWGGGWGGGGTTTGGGGWGGGGGGGGGGGGGTTTTTTTTTTTTTTTTTTWWW",
      "WGGGGGGWGGGWGGGGGGGGGGGWWWWWWWWWWWWWWWWWWWWWWGGGWWWGGGGWWW",
      "WGGGGGGWGGGWGGGGGGGGGGGWTTTTTTTTTTTTTTTTTTTTTGGGWWWGGGGTWW",
      "WGGGGGGWWWWWGGGGGGGGGGGWGGGGGGGGGGGGGGGGGGWWWWWWWWGGGGTTTW",
      "WGGGGGGGGGGGGGGGGGGGGGGWTTTTTTTTTTTTTGGGGGGGGGWWWWTTTTTTTW",
      "WGGGGGGGGGGGGGGGGGGGGGGWGGGGGGGGGGGGGGGGGGGGGGGGWGGGGGGGGW",
      "WGGGGGGGGGGGGGGGGGGGGGGWGGGGGGGGGGGGGGGGGGWWWWWWWWTTTTTTTW",
      "WWGGGGGGGGGGGGGGGGGGGGWWWWWTTTTTTTTTTTTTTTTGGGWWWWGGGGGGWW",
      "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
    ],
    signs: [
      { x: 8, y: 10, text: "The cave walls shimmer with trapped warmth." }
    ],
    triggers: [
      {
        x: 2,
        y: 13,
        kind: "cave-exit",
        targetMap: "sunmeadow",
        targetX: 27,
        targetY: 6,
        message: "You emerge back into Sunmeadow."
      },
      {
        x: 45,
        y: 13,
        kind: "cave-exit",
        targetMap: "sunmeadow",
        targetX: 68,
        targetY: 1,
        message: "You emerge back into Sunmeadow."
      }
    ]
  },
  wayfarerHouse: {
    name: "Wayfarer Cottage",
    palette: { top: "#000000", bottom: "#020202" },
    encounterRate: -1,
    terrain: [
      "WWWWWWWWWW",
      "WRRRRRRRRW",
      "WRRRRRRRRW",
      "WRRRRRRRRW",
      "WRRRRRRRRW",
      "WRRRRRRRRW",
      "WRRRRRRRRW",
      "WWWWWWWWWW"
    ],
    signs: [
      { x: 5, y: 2, text: "A note reads: rest, explore, and return stronger." }
    ],
    triggers: [
      {
        x: 4,
        y: 6,
        kind: "door-exit",
        targetMap: "sunmeadow",
        targetX: 23,
        targetY: 13,
        message: "You step back outside."
      }
    ]
  }
};
