import { creatureTypes } from "./types.js";

export const DEFAULT_MOVE_MP_COST = 2;


const generatedMoveStats = [
  { power: 8, accuracy: 0.99, mpCost: DEFAULT_MOVE_MP_COST },
  { power: 10, accuracy: 0.98, mpCost: DEFAULT_MOVE_MP_COST },
  { power: 12, accuracy: 0.97, mpCost: 3 },
  { power: 14, accuracy: 0.96, mpCost: 4 },
  { power: 16, accuracy: 0.95, mpCost: 4 },
  { power: 18, accuracy: 0.94, mpCost: 5 },
  { power: 20, accuracy: 0.92, mpCost: 5 },
  { power: 22, accuracy: 0.9, mpCost: 6 },
  { power: 24, accuracy: 0.88, mpCost: 6 },
  { power: 26, accuracy: 0.86, mpCost: 7 },
  { power: 28, accuracy: 0.84, mpCost: 8 },
  { power: 30, accuracy: 0.82, mpCost: 9 },
  { power: 32, accuracy: 0.8, mpCost: 10 },
  { power: 34, accuracy: 0.78, mpCost: 11 },
  { power: 36, accuracy: 0.76, mpCost: 12 },
  { power: 38, accuracy: 0.74, mpCost: 13 },
  { power: 40, accuracy: 0.72, mpCost: 14 },
  { power: 42, accuracy: 0.69, mpCost: 15 },
  { power: 44, accuracy: 0.66, mpCost: 16 },
  { power: 46, accuracy: 0.80, mpCost: 17 }
];

function toMoveKey(type, name) {
  const parts = `${type} ${name}`
    .replace(/[^a-zA-Z0-9 ]/g, "")
    .split(/\s+/)
    .filter(Boolean);

  return parts
    .map((part, index) => {
      const lower = part.toLowerCase();
      return index === 0 ? lower : `${lower[0].toUpperCase()}${lower.slice(1)}`;
    })
    .join("");
}

function generatedMovesForType(type, color, moves) {
  return Object.fromEntries(
    moves.map((move, index) => {
      const moveDef = typeof move === "string" ? { name: move } : move;
      const { name, tier = index, ...overrides } = moveDef;
      const stats = generatedMoveStats[tier] ?? generatedMoveStats[generatedMoveStats.length - 1];
      return [toMoveKey(type, name), { type, name, color, tier, ...stats, ...overrides }];
    })
  );
}

export const moveCatalog = {
  bump: { type: creatureTypes.STONE, name: "Bump", power: 10, accuracy: 0.9, color: "#d86c42", mpCost: 1 },
  bugBite: { type: creatureTypes.POISON, name: "Bug Bite", power: 18, accuracy: 0.9, color: "#81d842", mpCost: 3 },
  ember: { type: creatureTypes.FIRE, name: "Ember", power: 16, accuracy: 0.92, color: "#ef6c3e", mpCost: 5 },
  vineSnap: { type: creatureTypes.NATURE, name: "Vine Snap", power: 14, accuracy: 0.95, color: "#2d8f64", mpCost: 4 },
  iceShard: { type: creatureTypes.ICE, name: "Ice Shard", power: 25, accuracy: 0.5, color: "#9af0f0", mpCost: 8 },
  leafNeedle: { type: creatureTypes.NATURE, name: "Leaf Needle", power: 10, accuracy: 0.98, color: "#5dbb63", mpCost: 3 },
  rootJab: { type: creatureTypes.NATURE, name: "Root Jab", power: 12, accuracy: 0.96, color: "#7a9f43", mpCost: 4 },
  thornBurst: { type: creatureTypes.NATURE, name: "Thorn Burst", power: 18, accuracy: 0.9, color: "#2f9e44", mpCost: 5 },
  brambleCrash: { type: creatureTypes.NATURE, name: "Bramble Crash", power: 28, accuracy: 0.78, color: "#2f6f3e", mpCost: 9 },
  petalCyclone: { type: creatureTypes.NATURE, name: "Petal Cyclone", power: 24, accuracy: 0.84, color: "#f58fc3", mpCost: 8 },
  emberFlick: { type: creatureTypes.FIRE, name: "Ember Flick", power: 9, accuracy: 0.98, color: "#ff9f43", mpCost: 3 },
  flareBite: { type: creatureTypes.FIRE, name: "Flare Bite", power: 20, accuracy: 0.88, color: "#e8590c", mpCost: 6 },
  cinderRush: { type: creatureTypes.FIRE, name: "Cinder Rush", power: 26, accuracy: 0.82, color: "#d9480f", mpCost: 8 },
  moltenPounce: { type: creatureTypes.FIRE, name: "Molten Pounce", power: 34, accuracy: 0.72, color: "#b02a1f", mpCost: 11 },
  sunflare: { type: creatureTypes.FIRE, name: "Sunflare", power: 40, accuracy: 0.68, color: "#f08c00", mpCost: 13 },
  waterPebble: { type: creatureTypes.WATER, name: "Water Pebble", power: 11, accuracy: 0.97, color: "#4dabf7", mpCost: 3 },
  streamLash: { type: creatureTypes.WATER, name: "Stream Lash", power: 17, accuracy: 0.92, color: "#228be6", mpCost: 5 },
  mistCut: { type: creatureTypes.WATER, name: "Mist Cut", power: 21, accuracy: 0.88, color: "#74c0fc", mpCost: 6 },
  tidalToss: { type: creatureTypes.WATER, name: "Tidal Toss", power: 30, accuracy: 0.76, color: "#1864ab", mpCost: 10 },
  frostNip: { type: creatureTypes.ICE, name: "Frost Nip", power: 13, accuracy: 0.94, color: "#a5d8ff", mpCost: 4 },
  snowPierce: { type: creatureTypes.ICE, name: "Snow Pierce", power: 19, accuracy: 0.9, color: "#91e2f5", mpCost: 6 },
  glacierDrop: { type: creatureTypes.ICE, name: "Glacier Drop", power: 36, accuracy: 0.7, color: "#5bc0de", mpCost: 12 },
  stoneTap: { type: creatureTypes.STONE, name: "Stone Tap", power: 12, accuracy: 0.97, color: "#8d6e63", mpCost: 4 },
  pebbleBarrage: { type: creatureTypes.STONE, name: "Pebble Barrage", power: 22, accuracy: 0.85, color: "#7c6f64", mpCost: 7 },
  graniteSlam: { type: creatureTypes.STONE, name: "Granite Slam", power: 32, accuracy: 0.74, color: "#5c534d", mpCost: 10 },
  mudHook: { type: creatureTypes.STONE, name: "Mud Hook", power: 16, accuracy: 0.91, color: "#8a5a44", mpCost: 5 },
  gustPeck: { type: creatureTypes.FLYING, name: "Gust Peck", power: 10, accuracy: 0.98, mpCost: 3 },
  windShear: { type: creatureTypes.FLYING, name: "Wind Shear", power: 23, accuracy: 0.86, color: "#6ec6ff", mpCost: 7 },
  stormDive: { type: creatureTypes.FLYING, name: "Storm Dive", power: 35, accuracy: 0.72, color: "#4dabf7", mpCost: 11 },
  staticTap: { type: creatureTypes.LIGHTNING, name: "Static Tap", power: 8, accuracy: 0.99, color: "#fff176", mpCost: 2 },
  chargeZap: { type: creatureTypes.LIGHTNING, name: "Charge Zap", power: 10, accuracy: 0.97, color: "#ffe066", mpCost: 3 },
  sparkNibble: { type: creatureTypes.LIGHTNING, name: "Spark Nibble", power: 12, accuracy: 0.95, color: "#ffd43b", mpCost: 4 },
  voltJolt: { type: creatureTypes.LIGHTNING, name: "Volt Jolt", power: 16, accuracy: 0.92, color: "#ffec3d", mpCost: 5 },
  sparkSting: { type: creatureTypes.LIGHTNING, name: "Spark Sting", power: 20, accuracy: 0.89, color: "#ffd60a", mpCost: 6 },
  currentClaw: { type: creatureTypes.LIGHTNING, name: "Current Claw", power: 23, accuracy: 0.86, color: "#fcc419", mpCost: 7 },
  arcLeap: { type: creatureTypes.LIGHTNING, name: "Arc Leap", power: 24, accuracy: 0.83, color: "#fab005", mpCost: 8 },
  relayBolt: { type: creatureTypes.LIGHTNING, name: "Relay Bolt", power: 28, accuracy: 0.8, color: "#f59f00", mpCost: 9 },
  coilSurge: { type: creatureTypes.LIGHTNING, name: "Coil Surge", power: 32, accuracy: 0.76, color: "#f08c00", mpCost: 10 },
  stormPulse: { type: creatureTypes.LIGHTNING, name: "Storm Pulse", power: 36, accuracy: 0.72, color: "#e67700", mpCost: 11 },
  thunderHorn: { type: creatureTypes.LIGHTNING, name: "Thunder Horn", power: 38, accuracy: 0.69, color: "#f59f00", mpCost: 12 },
  thunderCrash: { type: creatureTypes.LIGHTNING, name: "Thunder Crash", power: 42, accuracy: 0.65, color: "#d9480f", mpCost: 14 },
  plasmaCrown: { type: creatureTypes.LIGHTNING, name: "Plasma Crown", power: 46, accuracy: 0.61, color: "#b197fc", mpCost: 16 },
  shadowSwipe: { type: creatureTypes.SHADOW, name: "Shadow Swipe", power: 18, accuracy: 0.9, color: "#6f42c1", mpCost: 5 },
  moonClaw: { type: creatureTypes.SHADOW, name: "Moon Claw", power: 27, accuracy: 0.8, color: "#7048e8", mpCost: 9 },
  starfall: { type: creatureTypes.MAGIC, name: "Starfall", power: 42, accuracy: 0.65, color: "#845ef7", mpCost: 14 },
  focus: { type: creatureTypes.MAGIC, name: "Focus", power: 0, accuracy: 1, color: "#6c5ce7", buff: 5, mpCost: DEFAULT_MOVE_MP_COST },
  heal: { type: creatureTypes.LIGHT, name: "Heal", power: 0, accuracy: 1, color: "#2a9d8f", heal: 16, mpCost: DEFAULT_MOVE_MP_COST },
  ...generatedMovesForType(creatureTypes.WATER, "#228be6", [
    { name: "Ripple Jab", tier: 0 },
    { name: "Tide Lash", tier: 1 },
    { name: "Bubble Burst", tier: 2 },
    { name: "River Rush", tier: 3 },
    { name: "Aqua Bite", tier: 4 },
    { name: "Mist Veil", tier: 5 },
    { name: "Whirlpool Snap", tier: 6 },
    { name: "Flood Kick", tier: 7 },
    { name: "Rain Spear", tier: 8 },
    { name: "Coral Guard", tier: 9 },
    { name: "Foam Shot", tier: 10 },
    { name: "Deep Current", tier: 11 },
    { name: "Torrent Claw", tier: 12 },
    { name: "Wave Crash", tier: 13 },
    { name: "Splash Hook", tier: 14 },
    { name: "Drench Pulse", tier: 15 },
    { name: "Geyser Pop", tier: 16 },
    { name: "Ocean Roar", tier: 17 },
    { name: "Soak Strike", tier: 18 },
    { name: "Tidal Crush", tier: 19 }
  ]),
  ...generatedMovesForType(creatureTypes.FIRE, "#ef6c3e", [
    { name: "Ember Peck", tier: 0 },
    { name: "Flame Flick", tier: 1 },
    { name: "Cinder Swipe", tier: 2 },
    { name: "Heat Bite", tier: 3 },
    { name: "Blazing Rush", tier: 4 },
    { name: "Torch Burst", tier: 5 },
    { name: "Ash Cloud", tier: 6 },
    { name: "Flare Kick", tier: 7 },
    { name: "Scorch Claw", tier: 8 },
    { name: "Burn Pulse", tier: 9 },
    { name: "Wildfire Snap", tier: 10 },
    { name: "Lava Lash", tier: 11 },
    { name: "Fireball Hop", tier: 12 },
    { name: "Smoulder Guard", tier: 13 },
    { name: "Furnace Slam", tier: 14 },
    { name: "Sparkfang", tier: 15 },
    { name: "Molten Roar", tier: 16 },
    { name: "Inferno Spin", tier: 17 },
    { name: "Charcoal Jab", tier: 18 },
    { name: "Sunflame Strike", tier: 19 }
  ]),
  ...generatedMovesForType(creatureTypes.NATURE, "#2d8f64", [
    { name: "Vine Whip", tier: 0 },
    { name: "Leaf Dart", tier: 1 },
    { name: "Thorn Jab", tier: 2 },
    { name: "Moss Shot", tier: 3 },
    { name: "Seed Scatter", tier: 4 },
    { name: "Root Snare", tier: 5 },
    { name: "Petal Pulse", tier: 6 },
    { name: "Bark Bash", tier: 7 },
    { name: "Bloom Blast", tier: 8 },
    { name: "Ivy Claw", tier: 9 },
    { name: "Bramble Bite", tier: 10 },
    { name: "Pollen Puff", tier: 11 },
    { name: "Forest Rush", tier: 12 },
    { name: "Sprout Shield", tier: 13 },
    { name: "Razor Leaflet", tier: 14 },
    { name: "Herbal Mist", tier: 15 },
    { name: "Wild Growth", tier: 16 },
    { name: "Sap Strike", tier: 17 },
    { name: "Timber Slam", tier: 18 },
    { name: "Verdant Roar", tier: 19 }
  ]),
  ...generatedMovesForType(creatureTypes.STONE, "#8d6e63", [
    { name: "Pebble Pop", tier: 0 },
    { name: "Boulder Bash", tier: 1 },
    { name: "Granite Guard", tier: 2 },
    { name: "Rock Spike", tier: 3 },
    { name: "Gravel Shot", tier: 4 },
    { name: "Stone Bite", tier: 5 },
    { name: "Quarry Crash", tier: 6 },
    { name: "Crystal Jab", tier: 7 },
    { name: "Rubble Rush", tier: 8 },
    { name: "Cliff Slam", tier: 9 },
    { name: "Fossil Fang", tier: 10 },
    { name: "Marble Shield", tier: 11 },
    { name: "Shard Storm", tier: 12 },
    { name: "Mountain Push", tier: 13 },
    { name: "Obsidian Strike", tier: 14 },
    { name: "Rock Roll", tier: 15 },
    { name: "Gem Pulse", tier: 16 },
    { name: "Stonewall", tier: 17 },
    { name: "Canyon Crush", tier: 18 },
    { name: "Meteor Chip", tier: 19 }
  ]),
  ...generatedMovesForType(creatureTypes.LIGHTNING, "#ffd43b", [
    { name: "Spark Tap", tier: 0 },
    { name: "Bolt Bite", tier: 1 },
    { name: "Static Snap", tier: 2 },
    { name: "Thunder Rush", tier: 3 },
    { name: "Volt Jab", tier: 4 },
    { name: "Charge Pulse", tier: 5 },
    { name: "Flash Kick", tier: 6 },
    { name: "Storm Chain", tier: 7 },
    { name: "Zap Shot", tier: 8 },
    { name: "Current Talon", tier: 9 },
    { name: "Neon Dash", tier: 10 },
    { name: "Shock Veil", tier: 11 },
    { name: "Overload", tier: 12 },
    { name: "Thunder Fang", tier: 13 },
    { name: "Power Surge", tier: 14 },
    { name: "Lightning Spin", tier: 15 },
    { name: "Ion Burst", tier: 16 },
    { name: "Static Trap", tier: 17 },
    { name: "Crackle Roar", tier: 18 },
    { name: "Final Bolt", tier: 19 }
  ]),
  ...generatedMovesForType(creatureTypes.FLYING, "#6ec6ff", [
    { name: "Wing Slap", tier: 0 },
    { name: "Gust Jab", tier: 1 },
    { name: "Feather Flick", tier: 2 },
    { name: "Sky Dash", tier: 3 },
    { name: "Air Cutter", tier: 4 },
    { name: "Talon Tap", tier: 5 },
    { name: "Cloud Veil", tier: 6 },
    { name: "Dive Strike", tier: 7 },
    { name: "Gale Spin", tier: 8 },
    { name: "Updraft", tier: 9 },
    { name: "Wind Bite", tier: 10 },
    { name: "Plume Shot", tier: 11 },
    { name: "Cyclone Rush", tier: 12 },
    { name: "Soaring Kick", tier: 13 },
    { name: "Razor Feather", tier: 14 },
    { name: "Breeze Guard", tier: 15 },
    { name: "Storm Wing", tier: 16 },
    { name: "Aerial Snap", tier: 17 },
    { name: "Highwind Crash", tier: 18 },
    { name: "Sky Roar", tier: 19 }
  ]),
  ...generatedMovesForType(creatureTypes.MAGIC, "#845ef7", [
    { name: "Arcane Tap", tier: 0 },
    { name: "Mystic Pulse", tier: 1 },
    { name: "Charm Bolt", tier: 2 },
    { name: "Mana Flick", tier: 3 },
    { name: "Spell Spark", tier: 4 },
    { name: "Rune Guard", tier: 5 },
    { name: "Wand Jab", tier: 6 },
    { name: "Dream Dust", tier: 7 },
    { name: "Hex Pop", tier: 8 },
    { name: "Glitter Beam", tier: 9 },
    { name: "Starlight Fall", tier: 10 },
    { name: "Enchant Bite", tier: 11 },
    { name: "Spellbind", tier: 12 },
    { name: "Mystic Veil", tier: 13 },
    { name: "Aura Burst", tier: 14 },
    { name: "Moon Charm", tier: 15 },
    { name: "Mana Rush", tier: 16 },
    { name: "Rune Crash", tier: 17 },
    { name: "Wonder Strike", tier: 18 },
    { name: "Arcane Roar", tier: 19 }
  ]),
  ...generatedMovesForType(creatureTypes.ICE, "#91e2f5", [
    { name: "Frost Bite", tier: 0 },
    { name: "Snow Jab", tier: 1 },
    { name: "Icicle Shot", tier: 2 },
    { name: "Chill Pulse", tier: 3 },
    { name: "Frozen Claw", tier: 4 },
    { name: "Hail Burst", tier: 5 },
    { name: "Glacier Guard", tier: 6 },
    { name: "Ice Kick", tier: 7 },
    { name: "Cold Snap", tier: 8 },
    { name: "Shiver Fang", tier: 9 },
    { name: "Crystal Freeze", tier: 10 },
    { name: "Snowdrift", tier: 11 },
    { name: "Frost Veil", tier: 12 },
    { name: "Polar Slam", tier: 13 },
    { name: "Ice Spike", tier: 14 },
    { name: "Winter Rush", tier: 15 },
    { name: "Frozen Roar", tier: 16 },
    { name: "Slush Trap", tier: 17 },
    { name: "Blizzard Tap", tier: 18 },
    { name: "Permafrost Crush", tier: 19 }
  ]),
  ...generatedMovesForType(creatureTypes.POISON, "#81d842", [
    { name: "Venom Jab", tier: 0 },
    { name: "Toxic Bite", tier: 1 },
    { name: "Sludge Pop", tier: 2 },
    { name: "Acid Flick", tier: 3 },
    { name: "Sting Shot", tier: 4 },
    { name: "Fume Cloud", tier: 5 },
    { name: "Poison Puff", tier: 6 },
    { name: "Noxious Claw", tier: 7 },
    { name: "Taint Pulse", tier: 8 },
    { name: "Corrode", tier: 9 },
    { name: "Slime Guard", tier: 10 },
    { name: "Bitter Sting", tier: 11 },
    { name: "Venom Strike", tier: 12 },
    { name: "Acid Spray", tier: 13 },
    { name: "Toxic Trap", tier: 14 },
    { name: "Rot Touch", tier: 15 },
    { name: "Gloom Mist", tier: 16 },
    { name: "Poison Fang", tier: 17 },
    { name: "Ooze Rush", tier: 18 },
    { name: "Deadly Drip", tier: 19 }
  ]),
  ...generatedMovesForType(creatureTypes.SHADOW, "#6f42c1", [
    { name: "Night Jab", tier: 0 },
    { name: "Shade Bite", tier: 1 },
    { name: "Dark Flick", tier: 2 },
    { name: "Phantom Claw", tier: 3 },
    { name: "Gloom Rush", tier: 4 },
    { name: "Blackout", tier: 5 },
    { name: "Fear Pulse", tier: 6 },
    { name: "Shadow Veil", tier: 7 },
    { name: "Sneak Strike", tier: 8 },
    { name: "Dusk Fang", tier: 9 },
    { name: "Midnight Trap", tier: 10 },
    { name: "Void Tap", tier: 11 },
    { name: "Grim Swipe", tier: 12 },
    { name: "Shade Shot", tier: 13 },
    { name: "Creeping Mist", tier: 14 },
    { name: "Haunt Rush", tier: 15 },
    { name: "Hollow Cry", tier: 16 },
    { name: "Darkbind", tier: 17 },
    { name: "Nightmare Snap", tier: 18 },
    { name: "Eclipse Crush", tier: 19 }
  ]),
  ...generatedMovesForType(creatureTypes.LIGHT, "#f8ff95", [
    { name: "Glow Tap", tier: 0 },
    { name: "Shine Shot", tier: 1 },
    { name: "Radiant Jab", tier: 2 },
    { name: "Sunbeam", tier: 3 },
    { name: "Halo Guard", tier: 4 },
    { name: "Prism Pulse", tier: 5 },
    { name: "Gleam Bite", tier: 6 },
    { name: "Bright Rush", tier: 7 },
    { name: "Sparkle Veil", tier: 8 },
    { name: "Dawn Strike", tier: 9 },
    { name: "Flash Bang", tier: 10 },
    { name: "Lantern Burst", tier: 11 },
    { name: "Beacon Call", tier: 12 },
    { name: "Holy Flick", tier: 13 },
    { name: "Star Shine", tier: 14 },
    { name: "Luminous Claw", tier: 15 },
    { name: "Solar Snap", tier: 16 },
    { name: "Lightwave", tier: 17 },
    { name: "Pure Beam", tier: 18 },
    { name: "Radiance Roar", tier: 19 }
  ]),
  ...generatedMovesForType(creatureTypes.DRAGON, "#c8553d", [
    { name: "Scale Swipe", tier: 0 },
    { name: "Drake Bite", tier: 1 },
    { name: "Dragon Rush", tier: 2 },
    { name: "Ancient Roar", tier: 3 },
    { name: "Clawquake", tier: 4 },
    { name: "Wing Crush", tier: 5 },
    { name: "Scale Guard", tier: 6 },
    { name: "Ember Breath", tier: 7 },
    { name: "Tail Slam", tier: 8 },
    { name: "Dragon Pulse", tier: 9 },
    { name: "Wyvern Snap", tier: 10 },
    { name: "Elder Fang", tier: 11 },
    { name: "Mythic Charge", tier: 12 },
    { name: "Scale Shot", tier: 13 },
    { name: "Serpent Spin", tier: 14 },
    { name: "Dragon Veil", tier: 15 },
    { name: "Hoard Guard", tier: 16 },
    { name: "Ancient Flame", tier: 17 },
    { name: "Roaring Claw", tier: 18 },
    { name: "Titan Drake", tier: 19 }
  ])

};

export function getMoveCost(move) {
  return Number.isFinite(move?.mpCost) ? Math.max(0, Math.round(move.mpCost)) : DEFAULT_MOVE_MP_COST;
}
